/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    "index",
    {
      type: "category",
      label: "Clients",
      link: { type: "doc", id: "clients" },
      items: [
        {
          type: "autogenerated",
          dirName: "clients",
        },
      ],
    },
    {
      type: "category",
      label: "Server",
      link: { type: "doc", id: "server/guide" },
      items: [
        {
          type: "autogenerated",
          dirName: "server",
        },
      ],
    },
    {
      type: "category",
      label: "Enterprise",
      items: [
        {
          type: "autogenerated",
          dirName: "enterprise",
        },
      ],
    },
    {
      type: "category",
      label: "Code Style",
      link: { type: "doc", id: "code-style" },
      items: [
        {
          type: "autogenerated",
          dirName: "code-style",
        },
      ],
    },
    {
      type: "category",
      label: "Tools",
      link: { type: "doc", id: "tools" },
      items: [
        {
          type: "autogenerated",
          dirName: "tools",
        },
      ],
    },
  ],
  contributing: [
    { type: "autogenerated", dirName: "contributing" }
  ],
  architecture: [{ type: "autogenerated", dirName: "architecture" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
