/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  getting_started: ["index", { type: "autogenerated", dirName: "getting-started" }],
  contributing: [{ type: "autogenerated", dirName: "contributing" }],
  architecture: [{ type: "autogenerated", dirName: "architecture" }],
  security: [{ type: "autogenerated", dirName: "security" }],
};

module.exports = sidebars;
