name: Label

on:
  pull_request:

jobs:
  label:
    name: Label
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Label pull request
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          sync-labels: true # Remove labels if matches are removed
