name: Review PR comment

on:
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions: {}

jobs:
  review:
    name: Review
    if: |
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude'))
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Review with Claude Code
        uses: anthropics/claude-code-action@a5528eec7426a4f0c9c1ac96018daa53ebd05bc4 # v1.0.7
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_args:
            '--allowed-tools "Bash(gh search:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr
            view:*),Bash(gh pr list:*)"'
